list=[]
f1= int(input("Enter marks here:"))
list.append(f1)
f2= int(input("Enter marks here:"))
list.append(f2)
f3= int(input("Enter marks here:"))
list.append(f3)
f4= int(input("Enter marks here:"))
list.append(f4)
f5= int(input("Enter marks here:"))
list.append(f5)
f6= int(input("Enter marks here:"))
list.append(f6)
list.sort()
print(list )